# rows from bottom to top. Hotbar is row 1
# items in nbt format should be stored in items directory
# If `nbt` is set to true on item then property `item` must
# have name of nbt file
inventory:
  - row: 1
    slots:
    - item: minecraft:dirt
      slot: 9
      count: 10
  - row: 4
    slots:
    - item: minecraft:grass_block
      slot: 1

equipment:
  offhand:
    item: minecraft:compass
    name: "<bold><color:#DB5461>Choose Server</color></bold>"
  helmet:
  chestplate:
  leggings:
  boots: